### ISSUE TITLE
Scroll-spy component

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/mp-react-components#219]
For the new material details page, we're using a [Bulma menu](http://bulma.io/documentation/components/menu/). This is instantiated on the Dash side via a `html.Aside()` component. It would be useful to wrap this menu with a `ScrollSpy` component so that `is-active` can get set automatically.

For ease of development, we could say that the scroll spy is looking for any in-page anchor element linked to from the menu.

For an example menu, as defined from Dash, see:

```
html.Aside(
                    [
                        html.P("Table of Contents", className="menu-label",),
                        html.Ul(
                            [
                                html.Li(
                                    html.A(
                                        "Crystal Structure", href="#crystal_structure"
                                    )
                                ),
                                html.Li(
                                    [
                                        html.A("Properties", href="#properties"),
                                        html.Ul(
                                            [
                                                html.Li(
                                                    html.A(
                                                        "Electronic Structure",
                                                        href="#electronic_structure",
                                                    )
                                                ),
                                                html.Li(
                                                    html.A(
                                                        "Thermodynamic Properties",
                                                        href="#thermodynamic_properties",
                                                    )
                                                ),
                                            ]
                                        ),
                                    ],
                                ),
                            ]
                        )
                    ], className="menu", id="side-menu"
)
```

(apologies for indentation in example, edited on GitHub)

**Comment by codytodonnell** [comment]
Demos of the new Scrollspy component are in app.tsx in mp-react-components and in scrollspy_usage.py in dash-mp-components.

There are two known limitations right now: (1) without using react-router, the menu links can either snap sections into view and update the url hash link accordingly, or smooth scroll sections into view **without** updating the url. If the scrollspy will ultimately be operating in an app with react-router features, we can use the react-router-hash-link library to achieve both smooth scrolling and url updating. I have implemented a different library, react-hash-link which handles scrolling to anchor links on page load but does not affect scrolling when clicking a menu link. This probably won't be necessary if we switch to react-router-hash-link in the future.

**Comment by mkhorton** [comment]
Thanks @codytodonnell, I'll give this a go and see if I can understand the implementation too. From my own perspective I think setting the `is-active` class is the most important thing (so a user has a sense of where they are in the page) vs the smooth scrolling (which I think is neat but less important), what do you think?

**Comment by codytodonnell** [comment]
Agreed, smooth scrolling is not essential. The important things are the active class and the url. We can consider smooth scrolling a nice-to-have down the line. Best-case would be to have smooth scrolling be a configurable user preference but that is another nice-to-have down the line.

**Comment by mkhorton** [comment]
This is how the native `dcc.Link` component updates the url: https://github.com/plotly/dash-core-components/blob/dev/src/components/Link.react.js
