### ISSUE TITLE
Bug: `defaultZoom` in `Simple3DScene` not working

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/mp-react-components#220]
Defined here: https://github.com/materialsproject/mp-react-components/blob/a8e0cd3f0ebcdce808db783a09e442b360ddfb09/src/crystal-toolkit-components/components-v2/Simple3DScene/constants.ts#L91

The idea with Simple3DScene is that when a new scene gets defined, the zoom level is automatically set with respect to the bounding box dimensions of the root-level scene object, so that when the scene is rotated nothing gets clipped out of frame.

`zoomLevel` is intended to be a float between 0 and 1 to slightly modify this behavior, so that we can add some margin to the object, but it seems like this functionality was removed at some point.

**Comment by codytodonnell** [comment]
It appears that the camera's position is dynamically set here:
https://github.com/materialsproject/mp-react-components/blob/a8e0cd3f0ebcdce808db783a09e442b360ddfb09/src/crystal-toolkit-components/components-v2/Simple3DScene/Simple3DScene.ts#L535

But, the zoom level is hardcoded to 4:
https://github.com/materialsproject/mp-react-components/blob/a8e0cd3f0ebcdce808db783a09e442b360ddfb09/src/crystal-toolkit-components/components-v2/Simple3DScene/Simple3DScene.ts#L580

Are you expecting the zoom level to also be calculated to fit the object? Or are you expecting the defaultZoom setting to be used?

**Comment by mkhorton** [comment]
Yes, the idea is to zoom to fit the object, with `defaultZoom` a multiplicative factor, i.e. if `defaultZoom=1` then the camera will exactly fit the object, if `defaultZoom=0.8` then the camera will be zoomed out a little to effectively add some padding around the object.

There is a subtlety here though. What we really need is an additional switch for the zoom behavior. By default, it uses the bounding box of the object to calculate the zoom, so that if the object is really long "out of the page", if you rotate the object you will still be able to see all of it even without changing the zoom level.

However, there are use cases where we want essentially static images (e.g. in the table of contents), where interactivity is not enabled, so in these cases we want the default zoom to be set just based on what's visible (i.e. if the object is really long "out of the page" this doesn't matter, since we're viewing it face-on, and we want to zoom to fit).

**Comment by mkhorton** [comment]
Just to clarify, because it's an orthographic camera, the "zoom" is actually set on the camera itself, i.e. see:

https://github.com/materialsproject/mp-react-components/blob/54d6dd264c0f75e6f1513af3e194e58873d88252/src/crystal-toolkit-components/components-v2/Simple3DScene/Simple3DScene.ts#L558

**Comment by codytodonnell** [comment]
Fixed with https://github.com/materialsproject/mp-react-components/commit/d456725775e0623fcbc6ca4618776f3ad4f7c594

**Comment by mkhorton** [comment]
Thanks!
