### ISSUE TITLE
Bug: Simple3DScene, RangeError for some surfaces

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/mp-react-components#235]
This is a somewhat serious bug (blocking work).

Something in `makeSurfaces` is causing a `RangeError: Maximum call stack size exceeded.` This is a large surface, but one that should be plottable. Example json attached.

[bad_surface.ctk.json.zip](https://github.com/materialsproject/mp-react-components/files/5204278/bad_surface.ctk.json.zip)

**Comment by codytodonnell** [comment]
If you're not already on it, I will take a look at this tomorrow morning. I have not spent any time in the Simple3DScene code yet, but hopefully this isn't a far reaching bug.

**Comment by mkhorton** [comment]
Nope, I'm not on it. Would appreciate a pair of eyes. If you have questions about the code though I can help, I wrote the initial version (pre-typescript) so I'm fairly familiar.

**Comment by mkhorton** [comment]
I'm not sure if it's related, but there's possible an issue with the surface rendering when viewing at certain angles too. This example shows some translucency, but artifacts are present with solid surfaces too.

[Screen Recording 2020-09-10 at 6.54.30 PM.zip](https://github.com/materialsproject/mp-react-components/files/5205480/Screen.Recording.2020-09-10.at.6.54.30.PM.zip)
[GaN-fs-test.ctk.json.zip](https://github.com/materialsproject/mp-react-components/files/5205483/GaN-fs-test.ctk.json.zip)

**Comment by codytodonnell** [comment]
Fixed with [this commit](https://github.com/materialsproject/mp-react-components/commit/0e3418c880e430dc6a45d6148eacc7d7bde93c9c)
